//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserAuthentication
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_GetDetails
    {
        public int RoleId { get; set; }
        public string RoleDescription { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public int Uid { get; set; }
        public string Name { get; set; }
        public string UserId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> Role { get; set; }
    }
}
